### ISSUE TITLE
Issues with Version 2.9.3.v-4-2_11-201509031342-a29ebef

### ISSUE THREAD

**Issue by phancox** [scalatest/scalatest-eclipse-plugin#56]
After upgrading to version 2.9.3.v-4-2_11-201509031342-a29ebef, right-clicking in a test suite no longer offers ScalaTest as a run option.

When attempting to run an existing ScalaTest configuration, the following error is thrown

```
org.scalaide.core.internal.compiler.ScalaPresentationCompiler cannot be cast to scala.tools.nsc.interactive.CompilerControl
```

Reverted to previous version and everything works fine.  Updated to new version and above errors occur again.

**Comment by kiritsuku** [comment]
Not sure where exactly the problem comes from but I think it is not a problem in ScalaTest plugin but in the way how we bundle it together with the IDE. I'm working on it.

**Comment by dragos** [comment]
I think this is a problem in the scalatest build. It depends on the wrong version of the Scala compiler, 2.11.6 instead of 2.11.7. I think it was built against the wrong IDE update site.

Edit: If you check the MANIFEST file in the scalatest plugin included in the update site you'll see that it depends (strictly) on 2.11.6. That dependency is filled in by the `-Pset-versions` profile, picking up the compiler version based on the IDE update site. I think the issue is somewhere in that step.

**Comment by cheeseng** [comment]
@sschaef @dragos @phancox Interesting, this is the line I changed when building for RC2: 

https://github.com/scalatest/scalatest-eclipse-plugin/blob/master/ecosystem-build.sh#L66

I basically change it to: 

build scala-ide-4.0-2_11-luna http://download.scala-ide.org/sdk/lithium/e44/scala211/dev/site 2.11.7 e44-scala211-4.0 http://download.eclipse.org/releases/luna/

just changed the update site part, which seems like it is already using 2.11.7, not sure how it turns up as 2.11.6 up there, I wonder if this takes precedence over set-versions: 

https://github.com/scalatest/scalatest-eclipse-plugin/blob/nightly/pom.xml#L114

Let me know if it will help to rebuild the scalatest plugin.

**Comment by kiritsuku** [comment]
I fought the ecosystem build system and I'm quite sure now what the problem is but I have still no clue how to fix it. The ScalaTest plugin is built correctly, but when we build the update sites for Eclipse something wrong is happening. There is an older version of the plugin added to the update site instead of the most recent one. The next thing to do for me is to find out how to get the plugin bundling process to do what it should and load the most recent version of the ScalaTest plugin.

**Comment by dragos** [comment]
What branch are you building? I really don't see how the problem can be in the ecosystem build. The scalatest plugin itself has the wrong dependency information in the MANIFEST file. I don't think the ecosystem build modifies manifest files.

**Comment by dragos** [comment]
What branch are you building?

**Comment by dragos** [comment]
@cheeseng can you please stop building older versions? Since the version number practically the same to all of them, it's impossible to know what we're installing. You only need to build the latest one, for Luna and 2.11. Don't worry, the older update sites will not delete scalatest. So, here:

http://www.artima.com/newplugins3/combined-next/plugins/

We should only see one version of ScalaTest.

**Comment by cheeseng** [comment]
@dragos, noted, built one that include only single version for latest 4.2 rc.  :)
